title: dan-ward-bio.github.io
description: An e-portfolio
baseurl: "" # If this is a user site (username.github.io), leave this blank. If it's a project site, set it to the repository name.
url: "https://dan-ward-bio.github.io" # For a user site. For a project site, "https://username.github.io/repository"
collections:
  projects_lab:
    output: true
  projects_informatics:
    output: true
  projects_making:
    output: true
